import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { Wallet, Download, ArrowLeft, Calendar, FileText, Loader2 } from "lucide-react";
import { motion } from "framer-motion";
import Cookies from "js-cookie";
import heroImage from "../../../../../assets/img/pngLogo.png";

const BASE_URL = window.API_BASE_URL;
const getToken = () => Cookies.get("jobdekho_token") || sessionStorage.getItem("employeeToken") || sessionStorage.getItem("companyToken") || sessionStorage.getItem("accessToken");

const PayslipsPage = () => {
  const [payslips, setPayslips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(null);

  useEffect(() => {
    const fetchPayslips = async () => {
      const token = getToken();
      if (!token) return;
      try {
        const res = await fetch(`${BASE_URL}/payslips`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const data = await res.json();
        setPayslips(data.data || []);
      } catch {
        /* silent */
      } finally {
        setLoading(false);
      }
    };
    fetchPayslips();
  }, []);

  const handleDownload = async (payslipId) => {
    const token = getToken();
    if (!token) return;
    setDownloading(payslipId);
    try {
      const res = await fetch(`${BASE_URL}/payslips/${payslipId}/download`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (!res.ok) throw new Error("Download failed");
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `Payslip-${payslipId}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      a.remove();
    } catch {
      const toast = (await import("react-hot-toast")).default;
      toast.error("Failed to download payslip");
    } finally {
      setDownloading(null);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-emerald-50/30">
      <nav className="bg-white border-b border-emerald-100 px-6 flex items-center justify-between sticky top-0 z-50 shadow-sm">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-gradient-to-br from-emerald-500 to-emerald-600 rounded-lg flex items-center justify-center">
            <Wallet className="w-4 h-4 text-white" />
          </div>
          <Link to="/employee">
            <img src={heroImage} alt="HRMS" className="w-25 max-w-5xl object-contain rounded-3xl" />
          </Link>
        </div>
        <Link to="/employee" className="flex items-center gap-2 text-sm font-semibold text-gray-600 hover:text-emerald-600 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Dashboard
        </Link>
      </nav>

      <div className="max-w-4xl mx-auto px-6 py-8">
        <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
          <h1 className="text-3xl font-bold text-gray-800 mb-2">My Payslips</h1>
          <p className="text-gray-500">View and download your salary slips</p>
        </motion.div>

        {loading ? (
          <div className="flex items-center justify-center py-20">
            <Loader2 className="w-8 h-8 animate-spin text-emerald-500" />
          </div>
        ) : payslips.length === 0 ? (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-center py-20">
            <div className="w-20 h-20 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <FileText className="w-10 h-10 text-emerald-400" />
            </div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">No payslips yet</h3>
            <p className="text-gray-500">Your payslips will appear here once generated by your HR team.</p>
          </motion.div>
        ) : (
          <div className="space-y-4">
            {payslips.map((payslip, index) => (
              <motion.div
                key={payslip._id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.05 }}
                className="bg-white rounded-2xl shadow-lg shadow-emerald-100/30 border border-emerald-50 p-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
              >
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-emerald-400 to-emerald-600 flex items-center justify-center shrink-0">
                    <Wallet className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <h3 className="font-bold text-gray-900">
                      {payslip.month || payslip.period || "Salary Slip"}
                    </h3>
                    <div className="flex items-center gap-3 mt-1 text-sm text-gray-500">
                      <span className="flex items-center gap-1">
                        <Calendar className="w-3.5 h-3.5" />
                        {payslip.payDate ? new Date(payslip.payDate).toLocaleDateString("en-IN", { month: "short", year: "numeric" }) : "—"}
                      </span>
                      {payslip.netPay !== undefined && (
                        <span className="font-semibold text-emerald-600">
                          ₹{Number(payslip.netPay).toLocaleString("en-IN")}
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                <button
                  onClick={() => handleDownload(payslip._id)}
                  disabled={downloading === payslip._id}
                  className="flex items-center gap-2 px-5 py-2.5 bg-emerald-500 text-white rounded-xl font-semibold text-sm hover:bg-emerald-600 transition-colors disabled:opacity-50 shrink-0"
                >
                  {downloading === payslip._id ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    <Download className="w-4 h-4" />
                  )}
                  {downloading === payslip._id ? "Downloading..." : "Download PDF"}
                </button>
              </motion.div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default PayslipsPage;
